### PR TITLE
fixed: add decomposer interface implementation

### PR DESCRIPTION
**Pull request by kardianos**
For golang/go#30870

### CODE REVIEW

**Comment by kardianos** [comment]
Let me know if you think this is acceptable. Thanks!

**Comment by robaho** [comment]
Shouldn’t the Decomposer interface be defined in an external package so that it is shared across all implementations? Otherwise what is the use?

**Comment by kardianos** [comment]
In Go, interfaces don't need to be referenced to be implemented. I
carefully avoided any reference to external types. While I do have an
external definition, I'm carefully avoiding adding dependencies. So long as
any package defines the same interface, Go's duck typing handles the rest.

**Comment by robaho** [comment]
But then you don’t need to define an exported interface in the fixed package which is what the PR does.

**Comment by kardianos** [comment]
Correct. That is optional and for documentation only. I can remove it from
the PR if you want.

**Comment by kardianos** [comment]
I've updated the PR to remove the inline private interface definition.

**Pull request merged**
